import pptxgen from 'pptxgenjs';
import type { ProjectIdea } from '@/types';

export function exportToPPT(idea: ProjectIdea) {
  const pptx = new pptxgen();
  pptx.layout = 'LAYOUT_WIDE';
  pptx.author = 'FinalYear AI';
  pptx.title = idea.title;

  const accent = '8B5CF6';
  const dark = '0F0F0F';
  const light = 'F5F3FF';

  // Slide 1: Title
  const slide1 = pptx.addSlide();
  slide1.background = { color: dark };
  slide1.addText('FINAL YEAR PROJECT', { x: 0.5, y: 1.5, w: 12, h: 0.6, fontSize: 18, color: accent, bold: true, align: 'center' });
  slide1.addText(idea.title, { x: 0.5, y: 2.2, w: 12, h: 1.2, fontSize: 36, color: 'FFFFFF', bold: true, align: 'center' });
  slide1.addText('"' + idea.tagline + '"', { x: 0.5, y: 3.5, w: 12, h: 0.6, fontSize: 18, color: 'A78BFA', italic: true, align: 'center' });
  slide1.addText('Innovation Score: ' + idea.innovationScore + '/10  |  Generated by FinalYear AI', { x: 0.5, y: 5.5, w: 12, h: 0.5, fontSize: 14, color: '888888', align: 'center' });

  // Slide 2: Abstract / Problem
  const slide2 = pptx.addSlide();
  slide2.background = { color: 'FFFFFF' };
  slide2.addText('Abstract & Problem Statement', { x: 0.5, y: 0.4, w: 12, h: 0.7, fontSize: 28, color: accent, bold: true });
  slide2.addShape(pptx.ShapeType.rect, { x: 0.5, y: 1.1, w: 12, h: 0.04, fill: { color: accent } });
  slide2.addText(idea.problem, { x: 0.7, y: 1.4, w: 11.5, h: 2.5, fontSize: 18, color: '333333' });
  slide2.addText('Why This Will Impress Judges:', { x: 0.7, y: 4.2, w: 11.5, h: 0.5, fontSize: 16, color: accent, bold: true });
  slide2.addText(idea.whyImpress, { x: 0.7, y: 4.7, w: 11.5, h: 2.2, fontSize: 14, color: '555555' });

  // Slide 3: Objectives / Core Features
  const slide3 = pptx.addSlide();
  slide3.background = { color: 'FFFFFF' };
  slide3.addText('Objectives & Core Features', { x: 0.5, y: 0.4, w: 12, h: 0.7, fontSize: 28, color: accent, bold: true });
  slide3.addShape(pptx.ShapeType.rect, { x: 0.5, y: 1.1, w: 12, h: 0.04, fill: { color: accent } });
  idea.coreFeatures.forEach((feature, i) => {
    slide3.addText(String(i + 1) + '. ' + feature, { x: 0.7, y: 1.4 + i * 0.9, w: 11.5, h: 0.8, fontSize: 16, color: '333333' });
  });

  // Slide 4: Tech Stack
  const slide4 = pptx.addSlide();
  slide4.background = { color: 'FFFFFF' };
  slide4.addText('Technology Stack', { x: 0.5, y: 0.4, w: 12, h: 0.7, fontSize: 28, color: accent, bold: true });
  slide4.addShape(pptx.ShapeType.rect, { x: 0.5, y: 1.1, w: 12, h: 0.04, fill: { color: accent } });
  const stackEntries = Object.entries(idea.techStack).filter(([, v]) => v.length > 0);
  stackEntries.forEach(([key, items], i) => {
    const label = key.charAt(0).toUpperCase() + key.slice(1);
    const y = 1.4 + i * 1.1;
    slide4.addText(label, { x: 0.7, y: y, w: 2.5, h: 0.8, fontSize: 16, color: accent, bold: true, fill: { color: light }, align: 'left', valign: 'middle' });
    slide4.addText(items.join(', '), { x: 3.3, y: y, w: 9, h: 0.8, fontSize: 15, color: '333333', valign: 'middle' });
  });

  // Slide 5: Timeline / Roadmap
  const slide5 = pptx.addSlide();
  slide5.background = { color: 'FFFFFF' };
  slide5.addText('Development Timeline', { x: 0.5, y: 0.4, w: 12, h: 0.7, fontSize: 28, color: accent, bold: true });
  slide5.addShape(pptx.ShapeType.rect, { x: 0.5, y: 1.1, w: 12, h: 0.04, fill: { color: accent } });
  idea.roadmap.forEach((phase, i) => {
    const y = 1.4 + i * 1.3;
    slide5.addShape(pptx.ShapeType.roundRect, { x: 0.7, y: y, w: 2.5, h: 1.0, fill: { color: accent }, line: { color: accent } });
    slide5.addText(phase.phase, { x: 0.7, y: y, w: 2.5, h: 0.5, fontSize: 14, color: 'FFFFFF', bold: true, align: 'center', valign: 'middle' });
    slide5.addText(phase.weeks, { x: 0.7, y: y + 0.5, w: 2.5, h: 0.4, fontSize: 12, color: 'FFFFFF', align: 'center', valign: 'middle' });
    slide5.addText(phase.description, { x: 3.4, y: y, w: 9, h: 1.0, fontSize: 14, color: '333333', valign: 'middle' });
  });

  // Slide 6: Cost, Hardware & Future
  const slide6 = pptx.addSlide();
  slide6.background = { color: 'FFFFFF' };
  slide6.addText('Cost, Hardware & Future Scope', { x: 0.5, y: 0.4, w: 12, h: 0.7, fontSize: 28, color: accent, bold: true });
  slide6.addShape(pptx.ShapeType.rect, { x: 0.5, y: 1.1, w: 12, h: 0.04, fill: { color: accent } });
  slide6.addText('Estimated Cost:', { x: 0.7, y: 1.4, w: 5.5, h: 0.5, fontSize: 16, color: accent, bold: true });
  slide6.addText(idea.estimatedCost, { x: 0.7, y: 1.9, w: 5.5, h: 1.5, fontSize: 14, color: '333333' });
  slide6.addText('Hardware Needed:', { x: 6.5, y: 1.4, w: 5.5, h: 0.5, fontSize: 16, color: accent, bold: true });
  slide6.addText(idea.hardwareNeeded, { x: 6.5, y: 1.9, w: 5.5, h: 1.5, fontSize: 14, color: '333333' });
  slide6.addText('Future Enhancements:', { x: 0.7, y: 3.8, w: 11.5, h: 0.5, fontSize: 16, color: accent, bold: true });
  idea.futureEnhancements.forEach((enh, i) => {
    slide6.addText('- ' + enh, { x: 0.7, y: 4.3 + i * 0.6, w: 11.5, h: 0.5, fontSize: 14, color: '333333' });
  });

  pptx.writeFile({ fileName: idea.title.replace(/[^a-zA-Z0-9]/g, '_') + '_Presentation.pptx' });
}
