import type { ProjectIdea } from '@/types';

function badge(label: string, color: string): string {
  return '!' + label + '-blue' === label + '-blue' ? '' : '';
}

export function generateReadme(idea: ProjectIdea): string {
  const techBadges: string[] = [];
  const allTech = [
    ...idea.techStack.frontend,
    ...idea.techStack.backend,
    ...idea.techStack.aiml,
    ...idea.techStack.hardware,
    ...idea.techStack.database,
  ];

  const badgeColors: Record<string, string> = {
    'React': '61DAFB', 'Node.js': '339933', 'Express': '000000', 'Python': '3776AB',
    'TensorFlow': 'FF6F00', 'PyTorch': 'EE4C2C', 'PostgreSQL': '336791', 'MongoDB': '47A248',
    'Flask': '000000', 'Django': '092E20', 'Flutter': '02569B', 'React Native': '61DAFB',
    'Tailwind CSS': '06B6D4', 'Firebase': 'FFCA28', 'Redis': 'DC382D', 'OpenCV': '5C3EE8',
    'ESP32': 'E7E7E7', 'Arduino': '00979D', 'FastAPI': '009688', 'Socket.io': '010101',
    'Expo': '000020', 'Ethers.js': '6F42C1', 'IPFS': '65C2CB',
  };

  allTech.forEach((tech) => {
    const color = badgeColors[tech] || '8B5CF6';
    techBadges.push('![!' + tech + '](https://img.shields.io/badge/' + encodeURIComponent(tech) + '-' + color + '?style=for-the-badge&logo=' + encodeURIComponent(tech.toLowerCase().replace(/[^a-z0-9]/g, '')) + '&logoColor=white)');
  });

  const featuresList = idea.coreFeatures.map((f) => '- ' + f).join('\n');
  const roadmapTable = idea.roadmap.map((r) => '| ' + r.phase + ' | ' + r.weeks + ' | ' + r.description + ' |').join('\n');
  const futureList = idea.futureEnhancements.map((f) => '- ' + f).join('\n');

  const stackSection = [
    idea.techStack.frontend.length ? '**Frontend:** ' + idea.techStack.frontend.join(', ') : '',
    idea.techStack.backend.length ? '**Backend:** ' + idea.techStack.backend.join(', ') : '',
    idea.techStack.aiml.length ? '**AI/ML:** ' + idea.techStack.aiml.join(', ') : '',
    idea.techStack.hardware.length ? '**Hardware:** ' + idea.techStack.hardware.join(', ') : '',
    idea.techStack.database.length ? '**Database:** ' + idea.techStack.database.join(', ') : '',
  ].filter(Boolean).join('\n');

  return '# ' + idea.title + '\n\n' +
    '> ' + idea.tagline + '\n\n' +
    techBadges.join('\n') + '\n\n' +
    '---\n\n' +
    '## Abstract\n\n' +
    idea.problem + '\n\n' +
    '## Objectives\n\n' +
    featuresList + '\n\n' +
    '## Tech Stack\n\n' +
    stackSection + '\n\n' +
    '## Development Timeline\n\n' +
    '| Phase | Timeline | Description |\n' +
    '|-------|----------|-------------|\n' +
    roadmapTable + '\n\n' +
    '## Cost & Hardware\n\n' +
    '| Item | Details |\n|------|--------|\n' +
    '| Estimated Cost | ' + idea.estimatedCost + ' |\n' +
    '| Hardware Needed | ' + idea.hardwareNeeded + ' |\n\n' +
    '## Why This Project Stands Out\n\n' +
    idea.whyImpress + '\n\n' +
    '## Future Enhancements\n\n' +
    futureList + '\n\n' +
    '---\n\n' +
    '## Getting Started\n\n' +
    '```bash\n' +
    '# Clone the repository\n' +
    'git clone https://github.com/yourusername/' + idea.title.toLowerCase().replace(/[^a-z0-9]/g, '-') + '.git\n\n' +
    '# Install dependencies\n' +
    'npm install\n\n' +
    '# Set up environment variables\n' +
    'cp .env.example .env\n\n' +
    '# Run the development server\n' +
    'npm run dev\n' +
    '```\n\n' +
    '## Innovation Score\n\n' +
    '![Innovation](https://img.shields.io/badge/Innovation_Score-' + idea.innovationScore + '%2F10-8B5CF6?style=for-the-badge)\n\n' +
    '---\n\n' +
    'Generated by [FinalYear AI](https://bolt.new) - From Idea to Project\n';
}

export function downloadReadme(idea: ProjectIdea) {
  const content = generateReadme(idea);
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'README.md';
  a.click();
  URL.revokeObjectURL(url);
}
